[NVME_STORAGE]
path = /srv/filebrowser/NVMe_Storage
browseable = yes
read only = no
guest ok = no
valid users = YOUR_USER
force user = YOUR_USER
create mask = 0775
directory mask = 0775

[MEDIA_LIBRARY]
path = /srv/immich-library
browseable = yes
read only = no
guest ok = no
valid users = YOUR_USER
force user = YOUR_USER
create mask = 0775
directory mask = 0775
